apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-stock
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Quackusarle/NT114_manifests.git
    targetRevision: HEAD
    path: argocd/apps/mlops-stock
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops-stock
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
