apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runner
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://actions-runner-controller.github.io/actions-runner-controller
    chart: actions-runner-controller
    targetRevision: "0.23.7"
    helm:
      valuesObject:
        replicaCount: 0
        githubWebhookServer:
          enabled: false
        runner:
          enabled: true
          repository: Quackusarle/NT114_manifests
          replicas: 1
          labels:
            - self-hosted
            - k3s
            - mlops
  destination:
    server: https://kubernetes.default.svc
    namespace: actions-runner-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
