apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow-svc
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://community-charts.github.io/helm-charts
    chart: mlflow
    targetRevision: "1.8.1"
    helm:
      valuesObject:
        backendStore:
          postgres:
            enabled: true
            host: postgres-svc.mlops-infra.svc.cluster.local
            port: 5432
            database: mlflow
            user: mlflow
            passwordSecret: postgres-credentials
            passwordSecretKey: postgres-password
        artifactRoot:
          s3:
            enabled: false
        defaultArtifactRoot: "s3://stock-models-dacn/mlflow-artifacts"
        extraEnvVars:
          MLFLOW_S3_IGNORE_TLS: "true"
        service:
          type: ClusterIP
          port: 5000
        ingress:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops-infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
