apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow-local
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://community-charts.github.io/helm-charts
    chart: mlflow
    targetRevision: "1.8.1"
    helm:
      valuesObject:
        backendStore:
          postgres:
            enabled: false
        artifactRoot:
          s3:
            enabled: false
        extraSecretNamesForEnvFrom:
          - mlflow-credentials
        extraEnvVars:
          MLFLOW_S3_IGNORE_TLS: "true"
        service:
          type: ClusterIP
          port: 5000
        ingress:
          enabled: true
          className: traefik
          hosts:
            - host: mlflow.local
              paths:
                - path: /
                  pathType: Prefix
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops-infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
