apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: mlops-stock-runner
  namespace: actions-runner-system
spec:
  template:
    spec:
      repository: Quackusarle/MLOps-Stock
      labels:
        - self-hosted
        - k3s
        - mlops
      dockerEnabled: false
      resources:
        requests:
          cpu: "500m"
          memory: "512Mi"
        limits:
          cpu: "2"
          memory: "2Gi"
